### ISSUE TITLE
Add a selection sort algorithm

### ISSUE THREAD

**Issue by GDSC-IPS** [gdsc-ipsacademy/Competitive_Programming#1]
Add an algorithm for selection sort in this repository

**Comment by haki-user** [comment]
> I would love to add the selection sort algorithm, please assign me!!

Refer [here](https://github.com/gdsc-ipsacademy/Competitive_Programming/tree/main/algorithms/binary-search)

**Comment by Tulsi5990** [comment]
Please assign me this .

**Comment by haki-user** [comment]
> Please assign me this .

This issue is resolved. Please feel free to create a new one.
