### ISSUE TITLE
Add Bubble sort algorithm

### ISSUE THREAD

**Issue by haki-user** [gdsc-ipsacademy/Competitive_Programming#10]

**Comment by Pr0-C0der** [comment]
Hey, can you assign it to me? And do you want code or description of bubble sort? Also, where should I add it?

**Comment by haki-user** [comment]
> Hey, can you assign it to me? And do you want code or description of bubble sort? Also, where should I add it?

refer this: https://github.com/gdsc-ipsacademy/Competitive_Programming/tree/main/algorithms/binary-search

**Comment by haki-user** [comment]
> Hey, can you assign it to me? And do you want code or description of bubble sort? Also, where should I add it?

If possible add both code and description, put them in algorithms/bubble-sort

**Comment by Kedap** [comment]
Can I be in charge of putting the code in python?

**Comment by haki-user** [comment]
> Can I be in charge only of putting the code in python?
> 
> edit: I'm somewhat new to algorithms, I welcome any suggestions about my code (#21) :p

Your seems correct, I have merged your PR.
If possible add documentation too.

**Comment by deepak039543** [comment]
Hey @haki-user brother ,could you please assign this issue to me? I will write this algorithm in CPP.
