### ISSUE TITLE
Implement Radix sort

### ISSUE THREAD

**Issue by sidhartha2002** [gdsc-ipsacademy/Competitive_Programming#11]
**Hey Bro, plz assign me this issue so that I add a new sorting algorithm "RADIX SORT" to your repo under `Hacktoberfest`**.

**Comment by haki-user** [comment]
> **Hey Bro, plz assign me this issue so that I add a new sorting algorithm "RADIX SORT" to your repo under `Hacktoberfest`**.



> **Hey Bro, plz assign me this issue so that I add a new sorting algorithm "RADIX SORT" to your repo under `Hacktoberfest`**.

Refer [this](https://github.com/gdsc-ipsacademy/Competitive_Programming/tree/main/algorithms/binary-search)
