### ISSUE TITLE
Add selection sort algorithm in python

### ISSUE THREAD

**Issue by parag477** [gdsc-ipsacademy/Competitive_Programming#14]
Selection sort is already added but in cpp. We want you to add the same algorithm in  python(.py)

**Comment by Thejas0604** [comment]
Dear @parag477 

Okay assign me to that. Do I have to create a folder?

**Comment by GDSC-IPS** [comment]
@Thejas0604 you have been assigned

**Comment by haki-user** [comment]
> Dear @parag477
> 
> Okay assign me to that. Do I have to create a folder?

No don't create additional folder, just put it inside the selection sort folder

**Comment by Thejas0604** [comment]
@haki-user 
>No don't create additional folder, just put it inside the selection sort folder

Already done. Please check.
