### ISSUE TITLE
Add a merge sort algorithm

### ISSUE THREAD

**Issue by GDSC-IPS** [gdsc-ipsacademy/Competitive_Programming#2]
Add an algorithm for merge sorting

**Comment by Swarno-Coder** [comment]
@GDSC-IPS Assign me. !assign

**Comment by haki-user** [comment]
> @GDSC-IPS Assign me. !assign

Refer to [this](https://github.com/gdsc-ipsacademy/Competitive_Programming/tree/main/algorithms/binary-search)
